version: "3"
services:
  gelf:
    build: "./listener"
    ports:
      - "12201:12201/udp"
    volumes:
      - ./listener/logs:/srv/listener/logs
    networks:
    - kong-net
  httpbin:
    image: "kennethreitz/httpbin"
    ports:
      - "80:80"
    networks:
    - kong-net
  kong:
    build: "."
    volumes: 
    - ./declarative:/kong/declarative/
    - ./kong-plugin-log-gelf/kong/plugins/log-gelf:/usr/local/share/lua/5.1/kong/plugins/log-gelf
    environment:
    - "KONG_DATABASE=off"
    - "KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml" 
    - "KONG_PROXY_ACCESS_LOG=/dev/stdout" 
    - "KONG_ADMIN_ACCESS_LOG=/dev/stdout"
    - "KONG_PROXY_ERROR_LOG=/dev/stderr"
    - "KONG_ADMIN_ERROR_LOG=/dev/stderr"
    - "KONG_LOG_LEVEL=debug"
    - "KONG_ADMIN_LISTEN=0.0.0.0:8001"
    - "KONG_ADMIN_GUI_URL=http://localhost:8002"
    - "KONG_PROXY_LISTEN=0.0.0.0:8000"
    - "KONG_PLUGINS=bundled,log-gelf"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    restart: always
    networks:
      - kong-net
networks:
  kong-net:

